-- Deck E — On-Prem Install: six Graphics Studio rows + pitch deck links
-- Requires: 003_image_graphics.sql, 008_seed_deck_e_pitch_deck.sql (deck row)
-- AUTO-GENERATED by scripts/generate-deck-e-graphics-seed-sql.mjs
-- Edit src/utils/business-context/deck-e-slides/*.ts then: npm run generate:deck-e-graphics-seed

-- From 005_image_graphics_canvas_columns.sql (older Supabase may lack these columns)
ALTER TABLE public.image_graphics
  ADD COLUMN IF NOT EXISTS canvas_width_px INTEGER,
  ADD COLUMN IF NOT EXISTS canvas_height_px INTEGER;

UPDATE public.image_graphics
SET
  canvas_width_px = COALESCE(canvas_width_px, 1080),
  canvas_height_px = COALESCE(canvas_height_px, 1080)
WHERE canvas_width_px IS NULL OR canvas_height_px IS NULL;

ALTER TABLE public.image_graphics
  ALTER COLUMN canvas_width_px SET DEFAULT 1080,
  ALTER COLUMN canvas_height_px SET DEFAULT 1080;

-- Single-tenant: user_id optional (see 011_drop_image_graphics_user_fk.sql)
ALTER TABLE public.image_graphics
  DROP CONSTRAINT IF EXISTS image_graphics_user_id_fkey;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'image_graphics' AND column_name = 'user_id'
  ) THEN
    ALTER TABLE public.image_graphics ALTER COLUMN user_id DROP NOT NULL;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.pitch_deck_intro_slide_graphics (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  pitch_deck_id UUID NOT NULL REFERENCES public.pitch_decks (id) ON DELETE CASCADE,
  slide_key TEXT NOT NULL,
  image_graphic_id UUID REFERENCES public.image_graphics (id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (pitch_deck_id, slide_key)
);

CREATE INDEX IF NOT EXISTS idx_pitch_deck_intro_slide_graphics_deck_id
  ON public.pitch_deck_intro_slide_graphics (pitch_deck_id);

INSERT INTO public.image_graphics (id, title, canvas_width_px, canvas_height_px, metadata, created_at, updated_at)
VALUES
  ('de000000-0000-4000-8000-000000000201', 'Cover - On Premise', 1920, 1080, jsonb_build_object('generationStatus', 'complete', 'studioDraft', jsonb_build_object('tsx', $tsx_cover$export default function Slide() {
  return (
    <div className={styles.root}>
      <div className={styles.missionBand}>
        <p className={styles.kicker}>On-premise AI infrastructure</p>
        <div className={styles.mission}>
          <p className={styles.missionLead}>Your data. Your workflows. Your brain.</p>
        </div>
      </div>
      <div className={styles.footerStrip}>
        <span className={styles.footerLink}>luckeeapp.com</span>
      </div>
      <div className={styles.branding} aria-hidden>
        <svg className={styles.mark} viewBox="0 0 212 286" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M199.005 0.0665482C197.108 -0.183221 195.208 0.274403 193.665 1.3669L3.32023 129.596C0.904057 131.218 -0.349119 134.064 0.085027 136.94C0.51918 139.817 2.56374 142.176 5.32169 143.032L80.7433 166.434L8.03238 273.498C5.65471 276.487 5.90422 280.754 8.58061 283.464C11.257 286.173 15.5128 286.477 18.5477 284.154L208.443 155.785C210.859 154.163 212.112 151.317 211.678 148.441C211.244 145.564 209.199 143.205 206.441 142.349L133.721 119.785L204.025 11.7281C205.361 9.70909 205.661 7.15285 204.792 4.88107C203.924 2.60928 202.014 0.907865 199.681 0.276121C199.455 0.206262 199.23 0.136407 199.005 0.0665482ZM171.264 34.5851L115.457 119.786C114.129 121.777 113.847 124.277 114.64 126.494C115.452 128.749 117.288 130.489 119.576 131.168L186.893 152.055L42.493 249.936L99.233 166.503C100.56 164.512 100.842 162.012 100.05 159.795C99.2374 157.54 97.4017 155.8 95.1135 155.121L24.87 133.326L171.264 34.5851Z" fill="#FF7C1E" />
        </svg>
      </div>
    </div>
  );
}

const styles = {
  root: `
    relative mx-auto flex h-full min-h-0 w-full max-w-[1920px] flex-col overflow-hidden
    aspect-video bg-slate-950
  `,
  missionBand: `
    flex min-h-0 flex-1 flex-col justify-center px-20 pb-40 pt-28 text-left
  `,
  kicker: `
    mb-8 text-[15px] font-medium uppercase tracking-[0.22em] text-[#FF7C1E]
  `,
  missionLead: `
    m-0 max-w-[1280px] text-balance text-[52px] font-semibold leading-[1.12] tracking-[-0.02em] text-zinc-50
  `,
  missionLine: `
    m-0 max-w-[1100px] text-balance text-[30px] font-semibold leading-[1.2] tracking-[-0.015em] text-zinc-200
  `,
  footerStrip: `
    pointer-events-auto absolute inset-x-0 bottom-0 z-[15] flex w-full flex-row flex-wrap items-center gap-x-10 gap-y-3 px-20 py-10
  `,
  footerLink: `
    shrink-0 text-left text-[22px] font-semibold leading-none text-[#FF7C1E] underline-offset-[6px]
  `,
  contactName: `
    shrink-0 text-[22px] font-semibold leading-none text-zinc-300
  `,
  branding: `
    pointer-events-none absolute bottom-10 right-10 z-20
  `,
  mark: `
    h-14 w-auto shrink-0
  `,
};$tsx_cover$), 'deckE', jsonb_build_object('templateKey', 'cover', 'pitchDeckId', 'de000000-0000-4000-8000-000000000001')), now(), now()),
  ('de000000-0000-4000-8000-000000000202', 'Opportunity - On Premise', 1920, 1080, jsonb_build_object('generationStatus', 'complete', 'studioDraft', jsonb_build_object('tsx', $tsx_problem$export default function Slide() {
  return (
    <div className={styles.root}>
      <p className={styles.slideTag}>Opportunity</p>
      <main className={styles.main}>
        <div className={styles.stack}>
          <h1 className={styles.headline}>
            GPU boxes never really stop inferencing;
            <br />
            everyday people need AI on a schedule and a short list of what to do next.
          </h1>
          <p className={styles.subhead}>Your network. Your privacy.</p>
        </div>
      </main>
      <div className={styles.branding} aria-hidden>
        <svg className={styles.mark} viewBox="0 0 212 286" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M199.005 0.0665482C197.108 -0.183221 195.208 0.274403 193.665 1.3669L3.32023 129.596C0.904057 131.218 -0.349119 134.064 0.085027 136.94C0.51918 139.817 2.56374 142.176 5.32169 143.032L80.7433 166.434L8.03238 273.498C5.65471 276.487 5.90422 280.754 8.58061 283.464C11.257 286.173 15.5128 286.477 18.5477 284.154L208.443 155.785C210.859 154.163 212.112 151.317 211.678 148.441C211.244 145.564 209.199 143.205 206.441 142.349L133.721 119.785L204.025 11.7281C205.361 9.70909 205.661 7.15285 204.792 4.88107C203.924 2.60928 202.014 0.907865 199.681 0.276121C199.455 0.206262 199.23 0.136407 199.005 0.0665482ZM171.264 34.5851L115.457 119.786C114.129 121.777 113.847 124.277 114.64 126.494C115.452 128.749 117.288 130.489 119.576 131.168L186.893 152.055L42.493 249.936L99.233 166.503C100.56 164.512 100.842 162.012 100.05 159.795C99.2374 157.54 97.4017 155.8 95.1135 155.121L24.87 133.326L171.264 34.5851Z" fill="#FF7C1E" />
        </svg>
      </div>
    </div>
  );
}

const styles = {
  root: `
    relative mx-auto flex h-full min-h-0 w-full max-w-[1920px] flex-col overflow-hidden
    aspect-video bg-white
  `,
  slideTag: `
    pointer-events-none absolute left-10 top-8 z-20 text-[16px] font-medium uppercase tracking-[0.2em] text-gray-500
  `,
  main: `
    mx-auto flex min-h-0 w-full max-w-[1400px] flex-1 flex-col justify-center px-20 pb-24 pt-28 text-left
  `,
  stack: `
    flex w-full max-w-[1200px] flex-col gap-8
  `,
  emphasis: `
    font-semibold text-gray-950
  `,
  orange: `
    font-semibold text-[#FF7C1E]
  `,
  main: `
    flex min-h-0 w-full flex-1 flex-col justify-center px-20 pb-24 pt-28 text-left
  `,
  stack: `
    flex w-full max-w-[1280px] flex-col gap-8
  `,
  headline: `
    m-0 text-balance text-[52px] font-semibold leading-[1.12] tracking-[-0.02em] text-gray-900
  `,
  subhead: `
    m-0 text-[30px] font-medium leading-[1.2] tracking-[-0.015em] text-gray-700
  `,
  branding: `
    pointer-events-none absolute bottom-10 right-10 z-10
  `,
  mark: `
    h-14 w-auto shrink-0
  `,
};$tsx_problem$), 'deckE', jsonb_build_object('templateKey', 'problem', 'pitchDeckId', 'de000000-0000-4000-8000-000000000001')), now(), now()),
  ('de000000-0000-4000-8000-000000000203', 'Solution - On Premise', 1920, 1080, jsonb_build_object('generationStatus', 'complete', 'studioDraft', jsonb_build_object('tsx', $tsx_solution$export default function Slide() {
  return (
    <div className={styles.root}>
      <p className={styles.slideTag}>Solution</p>
      <main className={styles.main}>
        <div className={styles.stack}>
          <h1 className={styles.headline}>
            Open-source modules on a menu.
            <br />
            Installed and maintained like traditional software.
          </h1>
          <p className={styles.subhead}>Mostly software. AI in bursts.</p>
          <ul className={styles.list}>
            <li className={styles.listItem}>
              <span className={styles.bullet} aria-hidden>·</span>
              <span>
                <span className={styles.emphasis}>AI Processes (AIP):</span> scheduled jobs with bounded scope.
              </span>
            </li>
            <li className={styles.listItem}>
              <span className={styles.bullet} aria-hidden>·</span>
              <span>
                <span className={styles.emphasis}>Next Best Actions (NBA):</span> AI ranks your next steps; you approve.
              </span>
            </li>
            <li className={styles.listItem}>
              <span className={styles.bullet} aria-hidden>·</span>
              <span>
                <span className={styles.emphasis}>Postgres and workflows:</span> tables and deterministic code run the
                day-to-day.
              </span>
            </li>
          </ul>
        </div>
      </main>
      <div className={styles.branding} aria-hidden>
        <svg className={styles.mark} viewBox="0 0 212 286" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M199.005 0.0665482C197.108 -0.183221 195.208 0.274403 193.665 1.3669L3.32023 129.596C0.904057 131.218 -0.349119 134.064 0.085027 136.94C0.51918 139.817 2.56374 142.176 5.32169 143.032L80.7433 166.434L8.03238 273.498C5.65471 276.487 5.90422 280.754 8.58061 283.464C11.257 286.173 15.5128 286.477 18.5477 284.154L208.443 155.785C210.859 154.163 212.112 151.317 211.678 148.441C211.244 145.564 209.199 143.205 206.441 142.349L133.721 119.785L204.025 11.7281C205.361 9.70909 205.661 7.15285 204.792 4.88107C203.924 2.60928 202.014 0.907865 199.681 0.276121C199.455 0.206262 199.23 0.136407 199.005 0.0665482ZM171.264 34.5851L115.457 119.786C114.129 121.777 113.847 124.277 114.64 126.494C115.452 128.749 117.288 130.489 119.576 131.168L186.893 152.055L42.493 249.936L99.233 166.503C100.56 164.512 100.842 162.012 100.05 159.795C99.2374 157.54 97.4017 155.8 95.1135 155.121L24.87 133.326L171.264 34.5851Z" fill="#FF7C1E" />
        </svg>
      </div>
    </div>
  );
}

const styles = {
  root: `
    relative mx-auto flex h-full min-h-0 w-full max-w-[1920px] flex-col overflow-hidden
    aspect-video bg-white
  `,
  slideTag: `
    pointer-events-none absolute left-10 top-8 z-20 text-[16px] font-medium uppercase tracking-[0.2em] text-gray-500
  `,
  main: `
    mx-auto flex min-h-0 w-full max-w-[1400px] flex-1 flex-col justify-center px-20 pb-24 pt-28 text-left
  `,
  stack: `
    flex w-full max-w-[1200px] flex-col gap-8
  `,
  emphasis: `
    font-semibold text-gray-950
  `,
  orange: `
    font-semibold text-[#FF7C1E]
  `,
  main: `
    flex min-h-0 w-full flex-1 flex-col justify-center px-20 pb-24 pt-28 text-left
  `,
  stack: `
    flex w-full max-w-[1280px] flex-col gap-8
  `,
  headline: `
    m-0 text-balance text-[52px] font-semibold leading-[1.12] tracking-[-0.02em] text-gray-900
  `,
  subhead: `
    m-0 text-[30px] font-medium leading-[1.2] tracking-[-0.015em] text-gray-700
  `,
  list: `
    m-0 flex list-none flex-col gap-5 p-0
  `,
  listItem: `
    flex gap-4 text-[28px] font-normal leading-[1.45] tracking-[-0.01em] text-gray-800
  `,
  bullet: `
    mt-1 shrink-0 text-[28px] font-bold leading-none text-[#FF7C1E]
  `,
  emphasis: `
    font-semibold text-gray-950
  `,
  branding: `
    pointer-events-none absolute bottom-10 right-10 z-10
  `,
  mark: `
    h-14 w-auto shrink-0
  `,
};$tsx_solution$), 'deckE', jsonb_build_object('templateKey', 'solution', 'pitchDeckId', 'de000000-0000-4000-8000-000000000001')), now(), now()),
  ('de000000-0000-4000-8000-000000000204', 'Market - On Premise', 1920, 1080, jsonb_build_object('generationStatus', 'complete', 'studioDraft', jsonb_build_object('tsx', $tsx_market$export default function Slide() {
  return (
    <div className={styles.root}>
      <p className={styles.slideTag}>Market</p>
      <main className={styles.main}>
        <div className={styles.stack}>
          <h1 className={styles.headline}>
            America has ~35M small businesses; ~18M households earn $200k–$1M.
          </h1>
          <div className={styles.columns}>
            <div className={styles.column}>
              <p className={styles.columnLabel}>Small businesses</p>
              <p className={styles.columnValue}>$175B</p>
            </div>
            <div className={styles.column}>
              <p className={styles.columnLabel}>Households</p>
              <p className={styles.columnValue}>$180B</p>
            </div>
          </div>
          <div className={styles.regionBlock}>
            <p className={styles.regionHeadline}>
              Starting in Philadelphia · Northeast (DC and up): ~7M small businesses; ~3.5M households earn
              $200k–$1M.
            </p>
            <div className={styles.regionColumns}>
              <div className={styles.column}>
                <p className={styles.regionLabel}>Small businesses</p>
                <p className={styles.regionValue}>$35B</p>
              </div>
              <div className={styles.column}>
                <p className={styles.regionLabel}>Households</p>
                <p className={styles.regionValue}>$35B</p>
              </div>
            </div>
          </div>
        </div>
      </main>
      <div className={styles.branding} aria-hidden>
        <svg className={styles.mark} viewBox="0 0 212 286" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M199.005 0.0665482C197.108 -0.183221 195.208 0.274403 193.665 1.3669L3.32023 129.596C0.904057 131.218 -0.349119 134.064 0.085027 136.94C0.51918 139.817 2.56374 142.176 5.32169 143.032L80.7433 166.434L8.03238 273.498C5.65471 276.487 5.90422 280.754 8.58061 283.464C11.257 286.173 15.5128 286.477 18.5477 284.154L208.443 155.785C210.859 154.163 212.112 151.317 211.678 148.441C211.244 145.564 209.199 143.205 206.441 142.349L133.721 119.785L204.025 11.7281C205.361 9.70909 205.661 7.15285 204.792 4.88107C203.924 2.60928 202.014 0.907865 199.681 0.276121C199.455 0.206262 199.23 0.136407 199.005 0.0665482ZM171.264 34.5851L115.457 119.786C114.129 121.777 113.847 124.277 114.64 126.494C115.452 128.749 117.288 130.489 119.576 131.168L186.893 152.055L42.493 249.936L99.233 166.503C100.56 164.512 100.842 162.012 100.05 159.795C99.2374 157.54 97.4017 155.8 95.1135 155.121L24.87 133.326L171.264 34.5851Z" fill="#FF7C1E" />
        </svg>
      </div>
    </div>
  );
}

const styles = {
  root: `
    relative mx-auto flex h-full min-h-0 w-full max-w-[1920px] flex-col overflow-hidden
    aspect-video bg-white
  `,
  slideTag: `
    pointer-events-none absolute left-10 top-8 z-20 text-[16px] font-medium uppercase tracking-[0.2em] text-gray-500
  `,
  main: `
    mx-auto flex min-h-0 w-full max-w-[1400px] flex-1 flex-col justify-center px-20 pb-24 pt-28 text-left
  `,
  stack: `
    flex w-full max-w-[1200px] flex-col gap-8
  `,
  emphasis: `
    font-semibold text-gray-950
  `,
  orange: `
    font-semibold text-[#FF7C1E]
  `,
  main: `
    flex min-h-0 w-full flex-1 flex-col justify-center px-20 pb-20 pt-24 text-left
  `,
  stack: `
    flex w-full flex-col gap-8
  `,
  headline: `
    m-0 w-full whitespace-nowrap text-[40px] font-semibold leading-[1.12] tracking-[-0.02em] text-gray-900
  `,
  columns: `
    grid w-full grid-cols-2 gap-16
  `,
  column: `
    flex min-w-0 flex-col gap-2
  `,
  columnLabel: `
    m-0 text-[24px] font-medium leading-[1.3] tracking-[-0.01em] text-gray-700
  `,
  columnValue: `
    m-0 text-[80px] font-semibold leading-none tracking-[-0.03em] text-[#FF7C1E]
  `,
  regionBlock: `
    flex w-full flex-col gap-5 border-t border-solid border-gray-200 pt-8
  `,
  regionHeadline: `
    m-0 w-full whitespace-nowrap text-[28px] font-semibold leading-[1.2] tracking-[-0.015em] text-gray-800
  `,
  regionColumns: `
    grid w-full grid-cols-2 gap-16
  `,
  regionLabel: `
    m-0 text-[20px] font-medium leading-[1.3] tracking-[-0.01em] text-gray-600
  `,
  regionValue: `
    m-0 text-[56px] font-semibold leading-none tracking-[-0.03em] text-[#FF7C1E]
  `,
  branding: `
    pointer-events-none absolute bottom-10 right-10 z-10
  `,
  mark: `
    h-14 w-auto shrink-0
  `,
};$tsx_market$), 'deckE', jsonb_build_object('templateKey', 'market', 'pitchDeckId', 'de000000-0000-4000-8000-000000000001')), now(), now()),
  ('de000000-0000-4000-8000-00000000020b', 'Ask - On Premise', 1920, 1080, jsonb_build_object('generationStatus', 'complete', 'studioDraft', jsonb_build_object('tsx', $tsx_ask$export default function Slide() {
  return (
    <div className={styles.root}>
      <p className={styles.slideTag}>Ask</p>
      <main className={styles.main}>
        <div className={styles.stack}>
          <h1 className={styles.headline}>
            <span className={styles.orange}>$500K</span>
            <span className={styles.headlineSep}> · </span>
            12 months
          </h1>
          <ul className={styles.list}>
            <li className={styles.listItem}>
              <span className={styles.bullet} aria-hidden>·</span>
              <span>Marketing and sales automation</span>
            </li>
            <li className={styles.listItem}>
              <span className={styles.bullet} aria-hidden>·</span>
              <span>Coding tokens and software subscriptions</span>
            </li>
            <li className={styles.listItem}>
              <span className={styles.bullet} aria-hidden>·</span>
              <span>
                <span className={styles.emphasis}>Field install:</span> one lead technician (electrician and
                carpenter), service truck, ethernet runs, device storage
              </span>
            </li>
          </ul>
        </div>
      </main>
      <div className={styles.branding} aria-hidden>
        <svg className={styles.mark} viewBox="0 0 212 286" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M199.005 0.0665482C197.108 -0.183221 195.208 0.274403 193.665 1.3669L3.32023 129.596C0.904057 131.218 -0.349119 134.064 0.085027 136.94C0.51918 139.817 2.56374 142.176 5.32169 143.032L80.7433 166.434L8.03238 273.498C5.65471 276.487 5.90422 280.754 8.58061 283.464C11.257 286.173 15.5128 286.477 18.5477 284.154L208.443 155.785C210.859 154.163 212.112 151.317 211.678 148.441C211.244 145.564 209.199 143.205 206.441 142.349L133.721 119.785L204.025 11.7281C205.361 9.70909 205.661 7.15285 204.792 4.88107C203.924 2.60928 202.014 0.907865 199.681 0.276121C199.455 0.206262 199.23 0.136407 199.005 0.0665482ZM171.264 34.5851L115.457 119.786C114.129 121.777 113.847 124.277 114.64 126.494C115.452 128.749 117.288 130.489 119.576 131.168L186.893 152.055L42.493 249.936L99.233 166.503C100.56 164.512 100.842 162.012 100.05 159.795C99.2374 157.54 97.4017 155.8 95.1135 155.121L24.87 133.326L171.264 34.5851Z" fill="#FF7C1E" />
        </svg>
      </div>
    </div>
  );
}

const styles = {
  root: `
    relative mx-auto flex h-full min-h-0 w-full max-w-[1920px] flex-col overflow-hidden
    aspect-video bg-white
  `,
  slideTag: `
    pointer-events-none absolute left-10 top-8 z-20 text-[16px] font-medium uppercase tracking-[0.2em] text-gray-500
  `,
  main: `
    mx-auto flex min-h-0 w-full max-w-[1400px] flex-1 flex-col justify-center px-20 pb-24 pt-28 text-left
  `,
  stack: `
    flex w-full max-w-[1200px] flex-col gap-8
  `,
  emphasis: `
    font-semibold text-gray-950
  `,
  orange: `
    font-semibold text-[#FF7C1E]
  `,
  main: `
    flex min-h-0 w-full flex-1 flex-col justify-center px-20 pb-24 pt-28 text-left
  `,
  stack: `
    flex w-full flex-col gap-8
  `,
  headline: `
    m-0 whitespace-nowrap text-[72px] font-semibold leading-none tracking-[-0.03em] text-gray-900
  `,
  headlineSep: `
    font-normal text-gray-400
  `,
  list: `
    m-0 flex list-none flex-col gap-5 p-0
  `,
  listItem: `
    flex gap-4 text-[28px] font-normal leading-[1.45] tracking-[-0.01em] text-gray-800
  `,
  bullet: `
    mt-1 shrink-0 text-[28px] font-bold leading-none text-[#FF7C1E]
  `,
  emphasis: `
    font-semibold text-gray-950
  `,
  branding: `
    pointer-events-none absolute bottom-10 right-10 z-10
  `,
  mark: `
    h-14 w-auto shrink-0
  `,
};$tsx_ask$), 'deckE', jsonb_build_object('templateKey', 'ask', 'pitchDeckId', 'de000000-0000-4000-8000-000000000001')), now(), now()),
  ('de000000-0000-4000-8000-00000000020c', 'Contact - On Premise', 1920, 1080, jsonb_build_object('generationStatus', 'complete', 'studioDraft', jsonb_build_object('tsx', $tsx_back_cover$export default function Slide() {
  return (
    <div className={styles.root}>
      <p className={styles.slideTag}>Contact</p>
      <main className={styles.main}>
        <div className={styles.stack}>
          <h1 className={styles.headline}>Matthew Ruiz</h1>
          <p className={styles.subhead}>Philadelphia · on-prem installs · open source at luckee-core</p>
          <div className={styles.links}>
            <a className={styles.link} href="mailto:matt@luckeeapp.com">
              matt@luckeeapp.com
            </a>
            <a className={styles.link} href="https://github.com/luckee-core" target="_blank" rel="noreferrer">
              github.com/luckee-core
            </a>
            <a className={styles.link} href="https://github.com/mzruiz" target="_blank" rel="noreferrer">
              github.com/mzruiz
            </a>
          </div>
        </div>
      </main>
      <div className={styles.branding} aria-hidden>
        <svg className={styles.mark} viewBox="0 0 212 286" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M199.005 0.0665482C197.108 -0.183221 195.208 0.274403 193.665 1.3669L3.32023 129.596C0.904057 131.218 -0.349119 134.064 0.085027 136.94C0.51918 139.817 2.56374 142.176 5.32169 143.032L80.7433 166.434L8.03238 273.498C5.65471 276.487 5.90422 280.754 8.58061 283.464C11.257 286.173 15.5128 286.477 18.5477 284.154L208.443 155.785C210.859 154.163 212.112 151.317 211.678 148.441C211.244 145.564 209.199 143.205 206.441 142.349L133.721 119.785L204.025 11.7281C205.361 9.70909 205.661 7.15285 204.792 4.88107C203.924 2.60928 202.014 0.907865 199.681 0.276121C199.455 0.206262 199.23 0.136407 199.005 0.0665482ZM171.264 34.5851L115.457 119.786C114.129 121.777 113.847 124.277 114.64 126.494C115.452 128.749 117.288 130.489 119.576 131.168L186.893 152.055L42.493 249.936L99.233 166.503C100.56 164.512 100.842 162.012 100.05 159.795C99.2374 157.54 97.4017 155.8 95.1135 155.121L24.87 133.326L171.264 34.5851Z" fill="#FF7C1E" />
        </svg>
      </div>
    </div>
  );
}

const styles = {
  root: `
    relative mx-auto flex h-full min-h-0 w-full max-w-[1920px] flex-col overflow-hidden
    aspect-video bg-white
  `,
  slideTag: `
    pointer-events-none absolute left-10 top-8 z-20 text-[16px] font-medium uppercase tracking-[0.2em] text-gray-500
  `,
  main: `
    mx-auto flex min-h-0 w-full max-w-[1400px] flex-1 flex-col justify-center px-20 pb-24 pt-28 text-left
  `,
  stack: `
    flex w-full max-w-[1200px] flex-col gap-8
  `,
  emphasis: `
    font-semibold text-gray-950
  `,
  orange: `
    font-semibold text-[#FF7C1E]
  `,
  main: `
    flex min-h-0 w-full flex-1 flex-col justify-center px-20 pb-24 pt-28 text-left
  `,
  stack: `
    flex w-full max-w-[1280px] flex-col gap-6
  `,
  headline: `
    m-0 text-[72px] font-semibold leading-none tracking-[-0.03em] text-gray-900
  `,
  subhead: `
    m-0 text-[30px] font-medium leading-[1.2] tracking-[-0.015em] text-gray-700
  `,
  links: `
    flex flex-col gap-4 pt-2
  `,
  link: `
    text-[28px] font-normal leading-[1.45] tracking-[-0.01em] text-gray-800 underline-offset-[6px] hover:text-[#FF7C1E] hover:underline
  `,
  branding: `
    pointer-events-none absolute bottom-10 right-10 z-10
  `,
  mark: `
    h-14 w-auto shrink-0
  `,
};$tsx_back_cover$), 'deckE', jsonb_build_object('templateKey', 'back_cover', 'pitchDeckId', 'de000000-0000-4000-8000-000000000001')), now(), now())
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  canvas_width_px = EXCLUDED.canvas_width_px,
  canvas_height_px = EXCLUDED.canvas_height_px,
  metadata = EXCLUDED.metadata,
  updated_at = now();

DELETE FROM public.pitch_deck_intro_slide_graphics
WHERE pitch_deck_id = 'de000000-0000-4000-8000-000000000001'
  AND slide_key NOT IN ('cover', 'problem', 'solution', 'market', 'ask', 'back_cover');

INSERT INTO public.pitch_deck_intro_slide_graphics (pitch_deck_id, slide_key, image_graphic_id, created_at, updated_at)
VALUES
  ('de000000-0000-4000-8000-000000000001', 'cover', 'de000000-0000-4000-8000-000000000201', now(), now()),
  ('de000000-0000-4000-8000-000000000001', 'problem', 'de000000-0000-4000-8000-000000000202', now(), now()),
  ('de000000-0000-4000-8000-000000000001', 'solution', 'de000000-0000-4000-8000-000000000203', now(), now()),
  ('de000000-0000-4000-8000-000000000001', 'market', 'de000000-0000-4000-8000-000000000204', now(), now()),
  ('de000000-0000-4000-8000-000000000001', 'ask', 'de000000-0000-4000-8000-00000000020b', now(), now()),
  ('de000000-0000-4000-8000-000000000001', 'back_cover', 'de000000-0000-4000-8000-00000000020c', now(), now())
ON CONFLICT (pitch_deck_id, slide_key) DO UPDATE SET
  image_graphic_id = EXCLUDED.image_graphic_id,
  updated_at = now();
